<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_dashboard  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_Dashboard_snippet( &$header, &$icon )
	{
		$header = "<div class='snip_title'>Used space</div><div class='snip_body'>49/50GB</div>";
echo "<div class='snip_link'><span class='fa fa-user'></span> Get more space</div>";;
	}
		// dashboatd snippets function
	function event_Dashboard_snippet1( &$header, &$icon )
	{
		$header = "<div class='snip_title'>My revenue</div><div class='snip_body'>$34,245</div>";
echo "<div class='snip_link'><span class='fa fa-dollar'></span> Last 24 hours</div>";;
	}
		// dashboatd snippets function
	function event_Dashboard_snippet2( &$header, &$icon )
	{
		$header = "<div class='snip_title'>Fixed issues</div><div class='snip_body'>75</div>";
echo "<div class='snip_link'><span class='fa fa-question-circle'></span> Tracked from Github</div>";;
	}
		// dashboatd snippets function
	function event_Dashboard_snippet3( &$header, &$icon )
	{
		$header = "<div class='snip_title'>Followers</div><div class='snip_body'>+245</div>";
echo "<div class='snip_link'><span class='fa fa-comment'></span> Just updated</div>";;
	}

}
?>